{
 "title": "Spring Boot Application Dashboard",
 "description": "Spring Boot Application Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"gateway\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    },
    {}
   ]
  }
 ]
}